### ISSUE TITLE
Child Mode

### ISSUE THREAD

**Issue by adrianlubitz** [jgoralcz/aki-api#46]
How can I use the Child Mode like on the Akinator Website?

Is there any option?

**Comment by whydie** [comment]
Is this package actually work? I get "KO - UNAUTHORIZED" all the time. 
Child mode is an optional query param "childMod", but doesn't seem like this code allows to add that parameter

**Comment by jgoralcz** [comment]
I was not aware child mode was a thing. You can submit a PR, and I'd happily accept it. Otherwise, I'll get around to it eventually.

**Comment by jgoralcz** [comment]
This should be working in 5.1.0

**Comment by adrianlubitz** [comment]
@whydie 
It works fine. Can you elaborate on the childMode parameter a little more? 
The fix from @jgoralcz did not work - Akinator still asks if my character is a porn actor :(

Is it maybe `childMode` instead of `childMod`?

**Comment by adrianlubitz** [comment]
I tried `childMode` but still doesn't work! 
@whydie @jgoralcz I couldn't find any API Documentation for the Akinator - how do you guys know which params can be passed?

**Comment by jgoralcz** [comment]
There is no official documentation. You can look into the network settings tab to see how it's calling their own API. Odd how the child mode doesn't work, they use `childMod`. Unfortunately it's hard to test without playing through the game a lot because of how random the questions can be.

**Comment by adrianlubitz** [comment]
I actually started doing that. There seems to be a `question_filter` parameter, which filters questions that are not for children. 
But unfortunately I still get the porn actor results in the end. I forked the project and I'm trying to get it working. I start a pull request, whenever it works 👍

**Comment by adrianlubitz** [comment]
Which tool do you use for that?

**Comment by adrianlubitz** [comment]
It seems like the only difference `childMod` makes is the image that is in the results.
And in childMode on the website they just don't show specific results and display a message saying `I know who you are thinking of, but I believe this is not for young people`
I don't know how they decide which results are not for young people. The only thing I could find is the `pseudo` field in the returned characters, which is as far as I can see it always `X` for porn actors.
I think this can't be managed in your api because the decision what needs to be done when a result is labeled `X` is on application side. You could either just ignore the fact that akinator thinks he found a result and play until you find one which is not `X` or like the page display some kind of disclaimer.
